### ISSUE TITLE
Authors_helper_spec generated with rails g? 

### ISSUE THREAD

**Issue by KristenLeach** [learn-co-curriculum/refactoring-views-with-helpers-reading#12]
Hello! I am not sure if this is the case, but it looks like someone might have done a rails generation and left in the rails tests. The spec/helpers/authors_heper_spec file has pending tests in it, and it is not mentioned in the lab.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @KristenLeach .

We have removed this file and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
