### ISSUE TITLE
Pending Test Appears To Prevent Student From Passing

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/refactoring-views-with-helpers-reading#13]
There is one pending test in the AuthorsHelper specs that causes the test suite to not be recognized as passing by learn-co. Commenting out this pending spec fixes the issue.

Also, the color option is not set in the `spec_helper.rb` file, which makes the tests much harder to read.

It can be set like this:

```ruby
RSpec.configure do |config|

  config.color = true

  ...
```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ecssiah.

We have removed the pending test and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
