### ISSUE TITLE
Walk Through Lab Has a Failing Test

### ISSUE THREAD

**Issue by sachinm78** [learn-co-curriculum/refactoring-views-with-helpers-reading#15]
After following along and posting the provided code, I was failing one test.  Here is the error:

`1) form shows an update form that submits content and redirects and prints out params
     Failure/Error: @post.update(params.require(:post))

     ActiveModel::ForbiddenAttributesError:
       ActiveModel::ForbiddenAttributesError
     # ./app/controllers/posts_controller.rb:22:in `update'`

To pass it, I changed the update method in posts_controller.rb to:

`def update
	  @post = Post.find(params[:id])
	  @post.update(params.require(:post).permit!)
	  redirect_to post_path(@post)
	end`

**Comment by helloamandamurphy** [comment]
Thanks for this! I used it and it worked for me as well!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
