### ISSUE TITLE
Needs strong params.

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/refactoring-views-with-helpers-reading#16]
In order to get the tests passing you will need to go into post_controller#update and pass in strong params and create a post_params method.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
