### ISSUE TITLE
helpers are bad news

### ISSUE THREAD

**Issue by JeffKatzy** [learn-co-curriculum/refactoring-views-with-helpers-reading#2]
I would prefer we teach view objects instead of helpers.  

Helpers are global throughout views, and thus don't really bring in benefits of separations of concerns.

**Comment by AnnJohn** [comment]
this might be more of a conversation between you guys, @JeffKatzy and @pletcher

**Comment by pletcher** [comment]
This seems like a good idea to me. I'll try to get around to it at some point, but in the meantime if anyone wants to open a PR, that'd be 💯

**Comment by DanielSeehausen** [comment]
This is a good point to bring up when considering what habits we should be instilling in students trying to understand how to implement general MVC guidelines. After review, we are going to be closing this issue for the following reasons:

1.) Rails diverges from a more 'pure' MVC implementation in several ways. The reduced barrier between the view and the controller (in which helpers can be implemented) is one such example. While this implementation may raise red flags when considering the importance of encapsulation, it is well within, and even encouraged by, the Rails standard:

"In addition to using the standard template helpers provided, **creating custom helpers to extract complicated logic or reusable functionality is strongly encouraged**..."
[](http://api.rubyonrails.org/classes/ActionController/Helpers.html)

As far as appropriateness of content, the example used in this readme represents (from what I have seen) the most commonly cited uses of these helpers: formatting a time string/providing a simple helper that is used by various views. 

2.) The lab appears to be trying to teach a core facet of Rails: use/creation of helpers and, while view objects are another important toolset for a Rails developer, the examples it uses appear to be appropriate for helpers. If we wanted to expand our lessons on view objects, perhaps an additional lab with an example that more strongly demonstrates their value could be used. (an alternative to altering this lab to be about view objects)
