### ISSUE TITLE
In the lesson hierarchy, the names of the second-to-lowest level might never be seen

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/refactoring-views-with-helpers-reading#5]
Flatiron curriculum's hierarchy has 4 levels. From top to bottom, they are:

- Track (e.g., Full Stack Web Dev. with React)
- Module (e.g., Intro to Ruby Development)
- Sub-module (e.g., Intro to Programming)
- Lesson (e.g., Intro to Tic Tac Toe)

Some Sub-module names (e.g., Full Stack Web Dev. with React > Rails > **Refactoring with Helpers and Model Methods**) are never seen by the student unless the student looks somewhere obscure, like the browser footer. That's because the left-hand nav truncates them (as it does all levels of the hierarchy), but the lesson-view shows only the top level (Track) and bottom level (Lesson). By that logic, some Module names might also never be seen, but, in practice, that appears to be rare, since Module names are concise.

**Comment by DanielSeehausen** [comment]
Hi there! This request sounds like an improvement to the Learn platform. Raising issues on GitHub should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface improvements. You can reach them at support@learn.co. Alternatively, if Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
